import pyautogui
import pyperclip
from time import sleep
pyautogui.press('win')
pyautogui.write('opera')
pyautogui.press('enter')
sleep(2)
pyautogui.write('https://web.whatsapp.com')
pyautogui.press('enter')
sleep(10)
pyautogui.click(x=458, y=171)
pyautogui.write('Meu amor')
sleep(2)
pyautogui.click(x=412, y=344)
sleep(0.5)
pyautogui.click(x=891, y=981)

pyautogui.write('Boa noite bb')
pyautogui.press('enter')
pyautogui.write('Dorme bem')
pyautogui.press('enter')
pyautogui.write('Sonha cmg')
pyautogui.press('enter')
pyautogui.write('Pensa em mim')
pyautogui.press('enter')
pyautogui.write('To pensando sempre em vc')
pyautogui.press('enter')
pyautogui.write('Te amo mais que tudo')
pyautogui.press('enter')
pyautogui.write('Pra sempre')
pyautogui.press('enter')
pyautogui.write('Beijão na boca')
pyautogui.press('enter')
pyautogui.write('Ate amanha')
pyautogui.press('enter')

